export const flowers = [
  {
    id: "chamomile-daisy",
    name: "Chamomile Daisy Bouquet",
    romanticMessage: "Like these pure daisies, my love for you is simple, bright, and unconditionally true.",
    meaning: "Purity, innocence, loyal love",
    season: "Spring to Summer",
    imageUrl: "/flowers/bouquet_1.webp",
    symbolism: "White petals represent pure intentions, yellow center represents sunlit warmth",
    funFact: "Chamomile flowers close up at night and open again with the first rays of the morning sun.",
    category: "new-baby",
    categoryLabel: "New Baby",
    designerTitle: "Daisy Serenade"
  },
  {
    id: "pink-carnations",
    name: "Blushing Carnation Bouquet",
    romanticMessage: "Every soft petal in this bouquet speaks of a love that grows deeper with every passing moment.",
    meaning: "Gratitude, mother's love, deep affection",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_2.webp",
    symbolism: "Pink carnations symbolize gratitude and a love that will never be forgotten",
    funFact: "Carnations were used in Greek ceremonial crowns and are one of the world's oldest cultivated flowers.",
    category: "anniversaries",
    categoryLabel: "Anniversaries",
    designerTitle: "Blushing Harmony"
  },
  {
    id: "spray-roses",
    name: "Sweet Petite Spray Roses",
    romanticMessage: "A cluster of delicate blossoms to show you that even the smallest moments with you are precious.",
    meaning: "Youthful joy, grace, sweet admiration",
    season: "Summer to Autumn",
    imageUrl: "/flowers/bouquet_3.webp",
    symbolism: "Pink spray roses reflect admiration, elegance, and soft romantic affection",
    funFact: "Spray roses produce multiple small blooms on a single stem, creating a naturally dense bouquet.",
    category: "birthdays",
    categoryLabel: "Birthday",
    designerTitle: "Sweet Whispers"
  },
  {
    id: "cream-roses",
    name: "Eucalyptus Cream Roses",
    romanticMessage: "Elegant and timeless, just like the bond we share that stands tall through all seasons.",
    meaning: "Charming grace, thoughtfulness, enduring bond",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_4.webp",
    symbolism: "Cream roses represent charm and grace, eucalyptus leaves symbolize protection and healing",
    funFact: "Eucalyptus leaves emit essential oils that help keep the roses fresh for longer periods.",
    category: "weddings",
    categoryLabel: "Wedding",
    designerTitle: "Classic Romance"
  },
  {
    id: "pink-lilies",
    name: "Majestic Pink Lily Bouquet",
    romanticMessage: "Your presence is as majestic and sweet-scented as the pink lilies in full bloom.",
    meaning: "Prosperity, abundance, sweet devotion",
    season: "Summer",
    imageUrl: "/flowers/bouquet_5.webp",
    symbolism: "Pink lilies represent wealth, prosperity, and a heart full of deep admiration",
    funFact: "Lilies are highly fragrant and have been depicted in murals dating back to 1580 B.C.",
    category: "weddings",
    categoryLabel: "Wedding",
    designerTitle: "Floral Fantasy"
  },
  {
    id: "peony-garden",
    name: "Blush Peony Gathering",
    romanticMessage: "With you, my heart flushes with joy—a beautiful garden of endless romance.",
    meaning: "Happy marriage, good fortune, bashful romance",
    season: "Spring to Early Summer",
    imageUrl: "/flowers/bouquet_6.webp",
    symbolism: "Pink peonies symbolize a happy life, marital bliss, and romantic prosperity",
    funFact: "Peonies can live and produce flowers for more than a hundred years if left undisturbed.",
    category: "anniversaries",
    categoryLabel: "Anniversaries",
    designerTitle: "Peony Dreams"
  },
  {
    id: "blush-roses",
    name: "Soft Blush Rose Bouquet",
    romanticMessage: "Nothing speaks more gently than a classic blush rose reflecting grace and sweet admiration.",
    meaning: "Grace, gentleness, sweet admiration",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_7.webp",
    symbolism: "Blush pink roses represent sweet affection, elegance, and pure gratitude",
    funFact: "Pink roses were the first color roses cultivated, as wild pink roses are the most common in nature.",
    category: "roses",
    categoryLabel: "Roses",
    designerTitle: "Blush Perfection"
  },
  {
    id: "newspaper-roses",
    name: "Vintage Crimson Spray",
    romanticMessage: "Our love story is vintage—classic, resilient, and beautifully written in our hearts.",
    meaning: "Vintage charm, classic romance, deep passion",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_8.webp",
    symbolism: "Deep red spray roses reflect passionate devotion, wrapping paper represents history",
    funFact: "Wrapping bouquets in vintage prints is an old Parisian tradition representing shared stories.",
    category: "roses",
    categoryLabel: "Roses",
    designerTitle: "Vintage Crimson"
  },
  {
    id: "pastel-mixed",
    name: "Garden Pastel Curation",
    romanticMessage: "You bring a colorful harmony of joy, laughter, and sweet warmth into my life.",
    meaning: "Harmony, joy, vibrant celebration",
    season: "Spring to Summer",
    imageUrl: "/flowers/bouquet_9.webp",
    symbolism: "Mixed pastels reflect a balance of joy, lighthearted friendship, and new beginnings",
    funFact: "A bouquet containing multiple varieties represents dynamic creativity and open communication.",
    category: "birthdays",
    categoryLabel: "Birthday",
    designerTitle: "Garden Melody"
  },
  {
    id: "deep-red-roses",
    name: "Classic Crimson Rose Selection",
    romanticMessage: "My love for you is as deep, red, and eternal as these classic roses.",
    meaning: "Eternal love, deep passion, absolute devotion",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_10.webp",
    symbolism: "Crimson red roses represent intense romantic love, passion, and mutual respect",
    funFact: "In Greek mythology, red roses were created by Aphrodite, the goddess of love.",
    category: "roses",
    categoryLabel: "Roses",
    designerTitle: "Royal Crimson"
  },
  {
    id: "sunflowers-craft",
    name: "Sun-Kissed Sunflowers",
    romanticMessage: "You are my sun; my heart naturally turns and blooms in your warmth.",
    meaning: "Loyalty, longevity, warmth and happiness",
    season: "Summer to Autumn",
    imageUrl: "/flowers/bouquet_11.webp",
    symbolism: "Bright yellow petals symbolize energy, strength, and unwavering loyalty",
    funFact: "Young sunflowers practice heliotropism—they face the sun from east to west every day.",
    category: "birthdays",
    categoryLabel: "Birthday",
    designerTitle: "Summer Serenade"
  },
  {
    id: "blue-delphinium",
    name: "Enchanted Sapphire Bouquet",
    romanticMessage: "Like the vast blue sky, my devotion to you is limitless and serene.",
    meaning: "Serenity, peace, infinite devotion",
    season: "Summer",
    imageUrl: "/flowers/bouquet_12.webp",
    symbolism: "Blue delphiniums represent lightheartedness, peace, and open opportunities",
    funFact: "Delphinium flowers derive their name from the Greek word for 'dolphin' due to their shape.",
    category: "anniversaries",
    categoryLabel: "Anniversaries",
    designerTitle: "Blue Enchantment"
  },
  {
    id: "peony-crimson",
    name: "Lush Pink Peony Selection",
    romanticMessage: "You are the sweetest chapter of my life, a bloom of endless warmth.",
    meaning: "Romance, elegance, bashful affection",
    season: "Spring",
    imageUrl: "/flowers/bouquet_13.webp",
    symbolism: "Lush pink peonies represent prosperity, happy marriage, and romance",
    funFact: "Peony petals are edible and have been used in traditional recipes for centuries.",
    category: "weddings",
    categoryLabel: "Wedding",
    designerTitle: "Peony Elegance"
  },
  {
    id: "pink-tulips",
    name: "Graceful Pink Tulips",
    romanticMessage: "A perfect declaration: I adore you, completely, wholly, and forever.",
    meaning: "Perfect love, caring affection, grace",
    season: "Late Winter to Spring",
    imageUrl: "/flowers/bouquet_14.webp",
    symbolism: "Pink tulips symbolize happiness, confidence, and warm caring feelings",
    funFact: "Tulips continue to grow in height even after being cut and placed in a vase.",
    category: "roses",
    categoryLabel: "Roses",
    designerTitle: "Tulip Splendor"
  },
  {
    id: "red-white-roses",
    name: "Devotion Rose Harmony",
    romanticMessage: "Our differences unite in a beautiful harmony of trust, respect, and love.",
    meaning: "Unity, mutual respect, shared devotion",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_15.webp",
    symbolism: "Red roses represent passion, while white roses symbolize pure, honest intentions",
    funFact: "A bouquet of red and white roses symbolizes unity, making it a popular choice for weddings.",
    category: "weddings",
    categoryLabel: "Wedding",
    designerTitle: "Love's Harmony"
  },
  {
    id: "mixed-daisies",
    name: "Vibrant Meadow Gathering",
    romanticMessage: "You bring the fresh, cheerful warmth of a sunny meadow into my heart.",
    meaning: "Cheerfulness, loyal love, fresh beginnings",
    season: "Spring to Autumn",
    imageUrl: "/flowers/bouquet_16.webp",
    symbolism: "Colorful daisies reflect dynamic joy, friendship, and lighthearted fun",
    funFact: "Daisies are composite flowers, meaning they are actually made of two flowers in one.",
    category: "new-baby",
    categoryLabel: "New Baby",
    designerTitle: "Meadow Melody"
  },
  {
    id: "hydrangea-blue",
    name: "Serene Hydrangea Cluster",
    romanticMessage: "Thank you for understanding me so completely, even in silence.",
    meaning: "Understanding, gratitude, heartfelt emotion",
    season: "Summer",
    imageUrl: "/flowers/bouquet_17.webp",
    symbolism: "Blue hydrangeas represent deep understanding, sincere gratitude, and calm thoughts",
    funFact: "The color of hydrangea blooms is determined by the acidity level of the soil they grow in.",
    category: "anniversaries",
    categoryLabel: "Anniversaries",
    designerTitle: "Heartfelt Serenity"
  },
  {
    id: "yellow-gerberas",
    name: "Golden Joy Gerberas",
    romanticMessage: "Your laughter is like a splash of golden sunshine on a cloudy day.",
    meaning: "Cheerfulness, sunlit warmth, pure happiness",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_18.webp",
    symbolism: "Yellow gerberas symbolize sunshine, pure happiness, and cheerful energy",
    funFact: "Gerbera daisies are the fifth most popular cut flower in the entire world.",
    category: "birthdays",
    categoryLabel: "Birthday",
    designerTitle: "Sunlit Cheer"
  },
  {
    id: "white-lilies-clean",
    name: "Pristine White Lilies",
    romanticMessage: "Your soul is pure, your heart is kind, and I am blessed to walk beside you.",
    meaning: "Purity, virtue, restored innocence",
    season: "Summer",
    imageUrl: "/flowers/bouquet_19.webp",
    symbolism: "White lilies represent virtue, clean beginnings, and pure majestic beauty",
    funFact: "In ancient Rome, lilies were used to stuff pillows and blankets for their sweet fragrance.",
    category: "new-baby",
    categoryLabel: "New Baby",
    designerTitle: "Pristine Grace"
  },
  {
    id: "blush-eucalyptus",
    name: "Eucalyptus Blush Gathering",
    romanticMessage: "A dreamy collection of soft blooms to remind you of my quiet, steady affection.",
    meaning: "Quiet affection, gentle care, comfort",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_20.webp",
    symbolism: "Soft blush blooms represent gentle care, while eucalyptus represents fresh comfort",
    funFact: "Eucalyptus has healing properties and is highly popular in modern luxury floral design.",
    category: "new-baby",
    categoryLabel: "New Baby",
    designerTitle: "Dreamy Comfort"
  }
];
