export const flowers = [
  {
    id: "lotus",
    name: "Lotus (कमल)",
    romanticMessage: "Like this lotus, our love rises pure and untouched from muddy waters.",
    meaning: "Purity, enlightenment, rebirth",
    season: "Jun to Oct",
    imageUrl: "/flowers/bouquet_floral_fantasy.png",
    symbolism: "Pink = love, white = purity, red = compassion",
    funFact: "National flower of India, sacred in Hindu & Buddhist culture",
    category: "weddings",
    categoryLabel: "Wedding",
    designerTitle: "Floral Fantasy",
    price: 150,
    originalPrice: 200
  },
  {
    id: "allamanda",
    name: "Allamanda (अलामंडा)",
    romanticMessage: "Like the golden trumpet's bloom, your presence fills my world with a bright, unfailing light.",
    meaning: "Joy, radiance, pure happiness",
    season: "May to Oct",
    imageUrl: "/flowers/bouquet_spring_serenade.png",
    symbolism: "Yellow = sunshine, growth, positivity",
    funFact: "Commonly called the 'Golden Trumpet' in India, it's known for its rapid growth and brilliant color.",
    category: "birthdays",
    categoryLabel: "Birthday",
    designerTitle: "Spring Serenade",
    price: 80,
    originalPrice: 150
  },
  {
    id: "jasmine",
    name: "Jasmine (चमेली)",
    romanticMessage: "Your grace lights up even the darkest night of my soul.",
    meaning: "Grace, elegance, sweetness",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_winter_whispers.png",
    symbolism: "Pure white = innocence, gold center = richness",
    funFact: "National flower essence of several Indian regions",
    category: "anniversaries",
    categoryLabel: "Anniversaries",
    designerTitle: "Winter Whispers",
    price: 100,
    originalPrice: null
  },
  {
    id: "sunflower",
    name: "Sunflower (सूरजमुखी)",
    romanticMessage: "You are my sun; everything in me naturally turns to face you.",
    meaning: "Loyalty, longevity, happiness",
    season: "Jul to Oct",
    imageUrl: "/flowers/bouquet_garden_charm.png",
    symbolism: "Yellow = happiness, strength, warmth",
    funFact: "Follows sun movement, metaphor for devotion",
    category: "birthdays",
    categoryLabel: "Birthday",
    designerTitle: "Garden Charm",
    price: 80,
    originalPrice: 180
  },
  {
    id: "rose",
    name: "Rose (गुलाब)",
    romanticMessage: "My love for you is as deep and red as the rose, eternal and unchanging.",
    meaning: "Eternal love, passion, devotion",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_rose_perfection.png",
    symbolism: "Red = deep romantic love, pink = gratitude, yellow = friendship",
    funFact: "Rose petals have been used in Indian royalty for fragrance and therapeutic baths.",
    category: "roses",
    categoryLabel: "Roses",
    designerTitle: "Rose Perfection",
    price: 200,
    originalPrice: null
  },
  {
    id: "peony",
    name: "Peony (पिओनी)",
    romanticMessage: "With you, I discover the meaning of 'bashful'—my heart flushes with love.",
    meaning: "Romance, prosperity, companionship",
    season: "Apr to Jun",
    imageUrl: "/flowers/bouquet_summer_symphony.png",
    symbolism: "Pink = sweetness, red = courage, white = bashfulness",
    funFact: "Symbolizes happy marriage in Asian cultures",
    category: "weddings",
    categoryLabel: "Wedding",
    designerTitle: "Summer Symphony",
    price: 180,
    originalPrice: null
  },
  {
    id: "cosmos",
    name: "Cosmos (कॉस्मॉस)",
    romanticMessage: "You bring harmony to my chaos, order to my universe.",
    meaning: "Order, harmony, modesty",
    season: "Aug to Oct",
    imageUrl: "/flowers/bouquet_winter_whispers.png",
    symbolism: "Pink = sweetness, white = purity, orange = joy",
    funFact: "Named after Greek word for 'universe,' represents cosmos harmony",
    category: "new-baby",
    categoryLabel: "New Baby",
    designerTitle: "Cosmic Harmony",
    price: 95,
    originalPrice: 130
  },
  {
    id: "tulip",
    name: "Tulip (तुलिप)",
    romanticMessage: "A perfect declaration: I adore you, completely and wholly.",
    meaning: "Perfect love, elegance, nobility",
    season: "Feb to Apr",
    imageUrl: "/flowers/bouquet_rose_perfection.png",
    symbolism: "Red = deep love, pink = caring, purple = royalty",
    funFact: "Grown in Himachal Pradesh, often called the Valentine flower",
    category: "roses",
    categoryLabel: "Roses",
    designerTitle: "Tulip Splendor",
    price: 120,
    originalPrice: 160
  },
  {
    id: "orchid",
    name: "Orchid (ऑर्किड)",
    romanticMessage: "Rare and magnificent—that's exactly what you are to me.",
    meaning: "Luxury, strength, rare beauty",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_floral_fantasy.png",
    symbolism: "Pink = femininity, white = elegance, purple = royalty",
    funFact: "Over 1,300 orchid species found in India",
    category: "anniversaries",
    categoryLabel: "Anniversaries",
    designerTitle: "Orchid Elegance",
    price: 115,
    originalPrice: null
  },
  {
    id: "marigold",
    name: "Marigold (गेंदा)",
    romanticMessage: "Bright as your smile, warm as your embrace—you complete me.",
    meaning: "Creativity, passion, warmth",
    season: "Sep to Nov",
    imageUrl: "/flowers/bouquet_summer_symphony.png",
    symbolism: "Orange = energy, yellow = happiness, red = deep love",
    funFact: "Sacred in Hindu ceremonies, symbol of auspiciousness",
    category: "weddings",
    categoryLabel: "Wedding",
    designerTitle: "Golden Celebration",
    price: 70,
    originalPrice: 100
  },
  {
    id: "hibiscus",
    name: "Hibiscus (गुड़हल)",
    romanticMessage: "You captivate me—your beauty is impossible to ignore, delicate yet bold.",
    meaning: "Delicate beauty, fleeting perfection",
    season: "Year-round",
    imageUrl: "/flowers/bouquet_spring_serenade.png",
    symbolism: "Pink = beauty, red = passion, white = purity",
    funFact: "Blooms for only one day, metaphor for cherishing moments",
    category: "birthdays",
    categoryLabel: "Birthday",
    designerTitle: "Vibrant Delight",
    price: 60,
    originalPrice: null
  },
  {
    id: "bougainvillea",
    name: "Bougainvillea (बुगनविल)",
    romanticMessage: "Vibrant, bold, unapologetically beautiful—like the love you inspire.",
    meaning: "Passion, vitality, resilience",
    season: "Nov to May",
    imageUrl: "/flowers/bouquet_garden_charm.png",
    symbolism: "Magenta = passion, pink = femininity, orange = enthusiasm",
    funFact: "Bright colors are actually bracts (modified leaves), not petals",
    category: "anniversaries",
    categoryLabel: "Anniversaries",
    designerTitle: "Resilient Grace",
    price: 85,
    originalPrice: 120
  },
  {
    id: "chrysanthemum",
    name: "Chrysanthemum (गुलदाउदी)",
    romanticMessage: "Through every season, my love for you remains eternal and true.",
    meaning: "Loyalty, devotion, immortal love",
    season: "Oct to Dec",
    imageUrl: "/flowers/bouquet_winter_whispers.png",
    symbolism: "Red = deep love, pink = affection, white = truth",
    funFact: "Symbol of fidelity, used in wedding arrangements",
    category: "new-baby",
    categoryLabel: "New Baby",
    designerTitle: "Bright Beginnings",
    price: 75,
    originalPrice: null
  }
];
